# Generated by Django 6.0.7 on 2026-08-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
    ]
